### PR TITLE
Apply roles to DBIx::Class::Objects::Base

### PR DESCRIPTION
**Pull request by dwburke**
I've found this quite helpful to reduce duplicate work.

### CODE REVIEW

**Comment by Ovid** [comment]
dwburke: Sadly, I am so friggin busy that I don't have time to maintain this? Would you like to take over and I'll give you co-maint on PAUSE?

**Comment by dwburke** [comment]
Sure, I have the time.  I would be honored to take over.

My PAUSE user is DBURKE.

Dan.

**Comment by Ovid** [comment]
Done. I've made you a collaborator here and give you co-maint on CPAN. Thank you! :)

**Comment by dwburke** [comment]
thank you!

**Comment by dwburke** [comment]
There's one package in there that you own, so I'm not able to push.. when
you get a chance can you add me to it?

Moose::Meta::Attribute::Custom::Trait::DBIC

Thanks,
Dan.

**Comment by Ovid** [comment]
Done. Sorry I missed that.

**Pull request merged**
